### ISSUE TITLE
Mobile friendly web page

### ISSUE THREAD

**Issue by gmarkomanolis** [IO500/webpage#29] opened 2020-08-04 16:24 UTC
Hi,

Having a mobile friendly web page would be great, to be able to see the menu from the main screen of the phone, for example difference

<img width="420" alt="mobile1" src="https://user-images.githubusercontent.com/2506875/89318472-d6556280-d64c-11ea-8960-bc56adc93ef9.png">

<img width="430" alt="mobile2" src="https://user-images.githubusercontent.com/2506875/89318492-dce3da00-d64c-11ea-9c03-62d37af05726.png">

**Comment by johnbent** [comment] 2020-08-07 20:16
Thanks @gmarkomanolis .  I fixed this in https://github.com/VI4IO/io-500-webpage/commit/59eeb259b0daa15d08ffb37f933e64b1d586d48d.  Please take a look at johnbent.io500.org and close this if you think this has been sufficiently addressed.

By the way, the tables will still require horizontal scrolling.  There is a weird thing we could do and turn them into tabular views when the screen is skinny but then there will be a lot of vertical scrolling.  Here's what it could look like:
![image](https://user-images.githubusercontent.com/2047294/89684725-4287ce80-d8b8-11ea-9bd3-c71b3d9909ed.png)

If you want to address the horizontal scrolling for tables, please create a new Issue for that and we can try the above approach.  Or we could also just do something like:
if screen is skinny: display link that says click here for table.
Then if you click on link, you get ONLY the table in the browser window.
I think this is not great because it's weird to be missing a table.  But this is an approach that some people like so we can certainly discuss it if you want.

Another approach is to only display the columns that fit and trim the rest but that's probably not what we want for IO500.

**Comment by johnbent** [comment] 2020-08-07 21:27
Closing.  Please re-open if issue persists.

**Comment by gmarkomanolis** [comment] 2020-08-17 18:40
sorry the background needs different color as the "500" disappears from the IO500:

![mob1](https://user-images.githubusercontent.com/2506875/90431604-4aedbf80-e097-11ea-827b-2950495aa6d8.jpg)

With horizontal direction of the device, the menu also is not correct:

![mob2](https://user-images.githubusercontent.com/2506875/90431633-58a34500-e097-11ea-8650-d040d923db4d.jpg)

compared to:

![mob3](https://user-images.githubusercontent.com/2506875/90431657-6062e980-e097-11ea-94db-d6b08fb53a46.jpg)

**Comment by jeanbez** [comment] 2020-09-04 18:13
@gmarkomanolis could you please check again in jbez.io500.org if the orientation is working as expected?

Could you also provide more details about the browser/OS and dark mode settings you used so that I can reproduce the color error in the logo? I could not reproduce it in my mobile.

**Comment by johnbent** [comment] 2020-09-25 20:22
Closing this as @jeanbez could not replicate and this is 21 days old

**Closed by johnbent** 2020-09-25 20:22 UTC
